# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0
auth_header:
  username_header: X-authentik-username

logger:
  default: info
  logs:
    custom_components.auth_header: debug
